### ISSUE TITLE
Method CustomizedVideoInput is not a registered operator.

### ISSUE THREAD

**Issue by jetyingjia** [facebookresearch/video-nonlocal-net#3]
Thank you for this outstanding work about nonlocal-net!
When I run this code, I get some mistakes.
Thank you in advance!

Traceback (most recent call last):
  File "../tools/train_net_video.py", line 264, in <module>
    main()
  File "../tools/train_net_video.py", line 260, in main
    train(args)
  File "../tools/train_net_video.py", line 101, in train
    test_model, test_timer, test_meter = create_wrapper(is_train=False)
  File "../tools/train_net_video.py", line 63, in create_wrapper
    model.build_model()
  File "/home/users/buyingjia/video-nonlocal-net-master/lib/models/model_builder_video.py", line 116, in build_model
    train=self.train, force_fw_only=self.force_fw_only
  File "/home/users/buyingjia/video-nonlocal-net-master/lib/models/model_builder_video.py", line 217, in create_data_parallel_model
    use_nccl=not cfg.DEBUG,  # org: True
  File "/home/users/buyingjia/caffe2/build/caffe2/python/data_parallel_model.py", line 45, in Parallelize_GPU
    Parallelize(*args, **kwargs)
  File "/home/users/buyingjia/caffe2/build/caffe2/python/data_parallel_model.py", line 206, in Parallelize
    input_builder_fun(model_helper_obj)
  File "/home/users/buyingjia/video-nonlocal-net-master/lib/models/model_builder_video.py", line 194, in add_video_input
    batch_size=batch_size,
  File "/home/users/buyingjia/video-nonlocal-net-master/lib/models/model_builder_video.py", line 159, in AddVideoInput
    data, label = model.net.CustomizedVideoInput(
  File "/home/users/buyingjia/caffe2/build/caffe2/python/core.py", line 2044, in __getattr__
    ",".join(workspace.C.nearby_opnames(op_type)) + ']'
AttributeError: Method CustomizedVideoInput is not a registered operator. Did you mean: []

Is thers something I forget to do?

**Comment by xiaolonw** [comment]
yes, you will need to install nccl, i have installed nccl from the official NVIDIA website. But you might try:
conda install -c anaconda nccl 
and then cmake and make again

**Comment by jetyingjia** [comment]
Sorry to trouble you again. I have two questions.
a.  In default, the broadcast_computed_params=True, I find in this porject(/lib/models/model_builder_video.py), broadcast_computed_params=False, the reason is ?

b. about the NCCL(terminate called after throwing an instance of 'caffe2::EnforceNotMet' what(): [enforce fail at cuda_nccl_gpu.cc:40] status == ncclSuccess. 2 vs 0. Error at: ), if I set the cfg.DEBUG=True, that means 
data_parallel_model.Parallelize_GPU(
            model,
            input_builder_fun=input_builder_fun,
            forward_pass_builder_fun=forward_pass_builder_fun,
            param_update_builder_fun=param_update_builder_fun,
            devices=gpus,
            rendezvous=rendezvous_ctx,
            broadcast_computed_params=False,
            optimize_gradient_memory=cfg.MODEL.MEMONGER,
            use_nccl=not cfg.DEBUG,  # org: True
        )
use_nccl=False, this problem can be solved. 
I worry is there effects on the performances.

Thank you in advance!

**Comment by kellycvcv** [comment]
Can you tell me how to solve the problem?"AttributeError: Method CustomizedVideoInput is not a registered operator. Did you mean: []"
I have  replace their video ops  by xiaolongs.
