### ISSUE TITLE
ImportError: cannot import name config

### ISSUE THREAD

**Issue by kellycvcv** [facebookresearch/video-nonlocal-net#9]
Hello,
    Thank you for the nice code.But I got a problem when I train the model.
Traceback (most recent call last):
  File "train_net_video.py", line 21, in <module>
    from core.config import config as cfg
ImportError: cannot import name config

Wait for your watch!

**Comment by caidonkey** [comment]
I also encountered this problem three days ago when I tested the pretrained models and has been stucked since then.
Traceback (most recent call last):
  File "../tools/test_net_video.py", line 26, in <module>
    from core.config import config as cfg
ImportError: No module named config

caffe2 has been installed following official tutorial (pip), not using Anaconda as your install example. However, python libs and modules mentioned in your install examples have all been installed using pip install.
I searched this problem for a long time and didn't get much information.

**Comment by xiaolonw** [comment]
have you set up your PYTHONPATH? 
export PYTHONPATH=/path/to/caffe2/build/install:/path/to/caffe2-video-nlnet/lib:$PYTHONPATH

**Comment by kellycvcv** [comment]
Thanks ！
It works well, and I write a __init__.py in  config foder!

**Comment by kevinlin311tw** [comment]
I also found similar errors. But finally it works with the latest pytorch. The problem is still not clear..
